# Project 1: Data Analysis with NumPy

In [1]:
import numpy as np

In [2]:
# Load the dataset
data = np.genfromtxt('Tesla.csv', delimiter=',', skip_header=1)

In [9]:
# Load the column names (first row of the CSV)
column_names = np.genfromtxt('Tesla.csv', delimiter=',', max_rows=1, dtype=str)

print("Column names:", column_names)

Column names: ['Date' 'Open' 'High' 'Low' 'Close' 'Volume' 'Adj Close']


In [10]:
data

array([[           nan, 1.90000000e+01, 2.50000000e+01, ...,
        2.38899990e+01, 1.87663000e+07, 2.38899990e+01],
       [           nan, 2.57900010e+01, 3.04200000e+01, ...,
        2.38300000e+01, 1.71871000e+07, 2.38300000e+01],
       [           nan, 2.50000000e+01, 2.59200000e+01, ...,
        2.19599990e+01, 8.21880000e+06, 2.19599990e+01],
       ...,
       [           nan, 2.57000000e+02, 2.61000000e+02, ...,
        2.55729996e+02, 4.81660000e+06, 2.55729996e+02],
       [           nan, 2.62399994e+02, 2.65750000e+02, ...,
        2.62049988e+02, 7.10040000e+06, 2.62049988e+02],
       [           nan, 2.64000000e+02, 2.65329987e+02, ...,
        2.61500000e+02, 6.47590000e+06, 2.61500000e+02]])

In [11]:
# Extract relevant columns 
open = data[:, 1]
high = data[:, 2]
low = data[:, 3]
close = data[:, 4]
volume = data[:, 5]
adj_close = data[:, 6]

In [12]:
# Stack the columns together for correlation calculation
data_matrix = np.stack((open, high, low, close, volume, adj_close), axis=0)

# Calculate the correlation matrix
correlation_matrix = np.corrcoef(data_matrix)

# Print the correlation matrix
print("Correlation matrix:\n", correlation_matrix)

Correlation matrix:
 [[1.         0.99962322 0.99960504 0.99923326 0.40751545 0.99923326]
 [0.99962322 1.         0.99952145 0.99969092 0.41646614 0.99969092]
 [0.99960504 0.99952145 1.         0.9996561  0.39761546 0.9996561 ]
 [0.99923326 0.99969092 0.9996561  1.         0.40690721 1.        ]
 [0.40751545 0.41646614 0.39761546 0.40690721 1.         0.40690721]
 [0.99923326 0.99969092 0.9996561  1.         0.40690721 1.        ]]


In [13]:
data.shape

(1692, 7)

In [14]:
data.size

11844

In [15]:
#calculates the mean
mean_values = np.mean(data, axis=0)
print("Mean values:", mean_values)

Mean values: [           nan 1.32441572e+02 1.34769698e+02 1.29996223e+02
 1.32428658e+02 4.27074090e+06 1.32428658e+02]


In [16]:
#calculates the median 
median_values = np.median(data, axis=0)
print("Median values:", median_values)

Median values: [           nan 1.56334999e+02 1.62370002e+02 1.53150002e+02
 1.58160004e+02 3.18070000e+06 1.58160004e+02]


In [17]:
#calculates the Standard Deviation
std_dev = np.std(data, axis=0)
print("Standard Deviation values:", std_dev)

Standard Deviation values: [           nan 9.42820498e+01 9.56666315e+01 9.28277838e+01
 9.42853123e+01 4.29470166e+06 9.42853123e+01]


In [20]:
#calculates the minimum values
min_values = np.min(data, axis=0)
print("Min values:", min_values)

Min values: [          nan 1.6139999e+01 1.6629999e+01 1.4980000e+01 1.5800000e+01
 1.1850000e+05 1.5800000e+01]


In [21]:
#calculates the maximum values
min_values = np.max(data, axis=0)
print("Max values:", min_values)

Max values: [           nan 2.87670013e+02 2.91420013e+02 2.80399994e+02
 2.86040009e+02 3.71639000e+07 2.86040009e+02]
